name: Lint README

on: push

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint README.md
      uses: avto-dev/markdown-lint@v1
      with:
        args: './README.md'
  link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install markdown-link-check
      run: npm install -g markdown-link-check
    - name: Check Markdown links
      run: markdown-link-check README.md --alive "200,403"